import './globals.css'
import { Inter } from 'next/font/google'
import { GlobalStateProvider } from './_context/global-context'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <head><meta charSet="utf-8" /></head> */}
      <body className={inter.className}>
        <GlobalStateProvider >
         {children}
        </GlobalStateProvider>
      </body>
    </html>
  )
}
