'use client'
import './globals.css'
import { useEffect, useState } from 'react'
import { Inter } from 'next/font/google'
import { GlobalStateProvider } from './_context/global-context'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  const [primaryColor, primayColorHandle] = useState({
    primary_bg : '',
    primary_font : ''
  })

  useEffect(() => {

    const brandingJSON = localStorage.getItem('planner');
    const branding = JSON.parse(brandingJSON);

    primayColorHandle({
      primary_bg : branding?.primary_bg,
      primary_font : branding?.primary_font
    })

  }, [])

  
  const branding = {
    primary_color: {
      backgroundColor: primaryColor?.primary_bg, 
      color: primaryColor?.primary_font,
    },

  };


  return (
    <html lang="en">
      {/* <head><meta charSet="utf-8" /></head> */}
      <body className={inter.className} style={branding.primary_color}>
        <GlobalStateProvider >
            {children}
        </GlobalStateProvider>

      </body>
    </html>
  )
}
